#cloud-config
package_upgrade: true

# bootcmd:
#   # Because of https://github.com/MicrosoftDocs/azure-docs/issues/82500
#   - systemctl mask waagent-apt.service

packages:
  # - apache2-utils
  # - nodejs
  # - npm
  - git
  - dnsutils

runcmd:
  # Install node js
  # Based on https://github.com/nodesource/distributions/blob/master/README.md
  - 'curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - '
  - 'sudo apt-get install -y nodejs'
  - 'sudo npm install -g npm@8.5.2'
  # Implement Node.js Server to run as service via pm2
  - 'git clone https://github.com/cpinotossi/cptdjswebsockets.git'
  - 'cd cptdjswebsockets'
  - 'npm install'
  - 'npm install pm2 -g'
  - 'chmod +x server.js'
  - 'pm2 start server.js -- ws.cptdagw.org 8000 009900 green'
